configured_endpoints: 12
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/trilitech%2Fjstz-client-d3de333a061bf9d9bc382cdb2a1ff6f2292ebac1758253a8b5a960f5f209a6d2.yml
openapi_spec_hash: d7a86bc8545cdc68cefad7cb6c035f62
config_hash: 988accea8481a880d62eaf9a3f29aed6
