configured_endpoints: 12
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/trilitech%2Fjstz-client-19557bed56f3923affaabb10df5cfd962147aeb7fdd01c2b63351bf9529d87ff.yml
openapi_spec_hash: ee6b71f12f7b4db161d0ef7f70923cf9
config_hash: 988accea8481a880d62eaf9a3f29aed6
